Guestbook/Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Guestbook.Data;
using Guestbook.Models;
using Guestbook.Services.Interfaces;

namespace Guestbook.Controllers
{
    public class GuestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;

        public GuestsController(ApplicationDbContext context, IImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        // GET: Guests
        public async Task<IActionResult> Index()
        {
            return View(await _context.Guests.ToListAsync());
        }

        // GET: Guests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guest = await _context.Guests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // GET: Guests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,Linkedin,Website,Message,Date,ImageData,ImageType,ImageFile,Id")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                if (guest.ImageFile != null)
                {
                    guest.ImageData = await _imageService.ConvertFileToByteArrayAsync(guest.ImageFile);
                    guest.ImageType = guest.ImageFile.ContentType;
                }

                _context.Add(guest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guest);
        }

        // GET: Guests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guest = await _context.Guests.FindAsync(id);
            if (guest == null)
            {
                return NotFound();
            }
            return View(guest);
        }

        // POST: Guests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Email,Linkedin,Website,Message,Date,ImageData,ImageType,Id")] Guest guest)
        {
            if (id != guest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestExists(guest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guest);
        }

        // GET: Guests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guest = await _context.Guests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // POST: Guests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guest = await _context.Guests.FindAsync(id);
            _context.Guests.Remove(guest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestExists(int id)
        {
            return _context.Guests.Any(e => e.Id == id);
        }
    }
}

Guestbook/Views/Shared/_Layout.cshtml
@{
    ViewData["App"] = "GUESTBOOK";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["App"]: A Coding Project by Lynda Foster</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/5db21ba9c6.js" crossorigin="anonymous"></script>
    <link href="/css/site.css" rel="stylesheet" />
    <link href="/css/prism.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Liu+Jian+Mao+Cao&family=Lora&display=swap" rel="stylesheet">
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand appname" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/img/brand.png" width="35" height="35" alt="zen icon" style="vertical-align:middle">
                    &nbsp @ViewData["App"]
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Overview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Guests" asp-action="Index">Guestbook</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Code">Code</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://lfost42-portfolio.netlify.app">About Me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container min-vh-100">
            <div class="container mt-4 py-5 px-5">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>


    <!-- ===== FOOTER SECTION ====== -->
    <footer class="border-top footer text-muted mt-auto py-3">
        <div class="container-fluid">
            <div class="row row-cols-1 row-cols-lg-3 gy-2">
                <div class="col texgt-light order-last order-lg-first">
                    <div><span span class="text-muted">&copy2021</span> Lynda Foster | Los Angeles, CA</div>
                </div>
                <div class="col d-flex align-items-start justify-content-start justify-content-lg-center">
                    <div class="row">
                        <div class="col social brand "><img src="/img/brand_light.png" height="25" width="254" alt="Lynda Foster Brand Logo"></div>
                    </div>
                </div>
                <div class="col d-flex align-items-center justify-content-start justify-content-lg-end">
                    <div class="row">
                        <div class="col social"><a href="https://www.linkedin.com/in/lynda-foster/"><i class="fab fa-linkedin fa-2x"></i></a></div>
                        <div class="col social"><a href="https://github.com/lfost42/"><i class="fab fa-github fa-2x"></i></a></div>
                        <div class="col social"><a href="https://lfost42-portfolio.netlify.app/"><img src="/img/icon.png" width="32" height="32" /></a></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
    </script>
    <script src="/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>